### ISSUE TITLE
When saving a change to a file in Xcode during a "Attach to process", after new app deploy and "Attach to process" the break points are not hit.

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-dev-debugging#2]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/) or the readme?
Yes

### Tell us about the problem
If a "Attach to process" is running in Xcode, after changing and saving a file in Xcode (Cmd + S), a new rebuild process is triggered and the app is deployed to the simulator. If you again try to "Attach to process" you are correctly attached but no break points in Xcode are hit.

In order to resolve this behavior you need to:
- Stop the process (the stop button in the menu strip) in Xcode before saving the changes to the source code 
or 
- Stop the `nd.run` command, do an `nd.clean.demo` (or manually remove the _platforms_ folder of that demo application) and again run `nd.run`

### Which platform(s) does your issue occur on?
_iOS/Android/Both (if applicable tell us the specific version of the platform)_

### Please provide the following version numbers that your issue occurs with:
- **nativescript-dev-debugging:** 1.0.0
- **CLI:** 5.1.1
- **Cross-platform modules:** ^5.1.0
- **Runtime(s):** 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start `nd.run` command
2. Chose demo > ios > attach & watch
3. After the native framework is build and the demo app is deployed in Xcode go to "Debug > Attach to Process by PID" > write "demo"
4. Add a break point to the native source code of the plugin's framework, it is correctly hit
5. Without stoping the "Attach to process" change the plugin's native code and save it (Cmd + S)
6 After a new framework build and demo app deploy attaching to its process leads to no break points being hit

**Comment by zbranzov** [comment]
Using the demo app I'm unable to attach to debug using the attach and watch. No break point is hit even once.
Using the vue app I was able to use break points just first time.
For testing I was using gauge plugin

**Comment by VladimirAmiorkov** [comment]
Resolved in 1.0.1
